### ISSUE TITLE
System.InvalidOperationException:  Request byte was unexpected. Expected 1, but got 1

### ISSUE THREAD

**Issue by CEiderEVIDENT** [gematik/lib-vau-csharp#3]
Hi,

I extend 
KemTest.cs from lib-vau-csharp-test/public void TestHandshake() by

```c#
            byte[] encryptedVauServerMessage3 = vauClientStateMachine.EncryptVauMessage(Encoding.ASCII.GetBytes("Hello World"));
            byte[] decryptedVauServerMessage3 = vauClientStateMachine.DecryptVauMessage(encryptedVauServerMessage3);
            Assert.AreEqual("Hello World", Encoding.UTF8.GetString(decryptedVauServerMessage3));
``` 
This results in System.InvalidOperationException:  Request byte was unexpected. Expected 1, but got 1

My idea was to encrypt some a string within client and let it decrypt again by the same client.
From my understanding this should result in the same string that has been encoded.

Is this an issue or is there some kind of misunderstanding on my mind?

Tia Carsten Eider

**Comment by CEiderEVIDENT** [comment]
![image](https://github.com/user-attachments/assets/2e390cba-a528-482b-8478-4af818425290)

**Comment by CEiderEVIDENT** [comment]
After a good night of thinking about the situation I found the knot of misunderstanding in my mind and understodd what I am doing wrong.
There is no real issue, except that the error message is a bit confusing: Expect 1 but got 1 ?????

**Comment by fnoGematik** [comment]
Hi @CEiderEVIDENT ,

I apologize for the confusion. The correct error message should actually be “Request byte was unexpected. Expected 2, but got 1”.
This will be fixed with the next update.

Best regards,
